# Generated by Django 2.0.5 on 2018-08-06 20:52

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='index',
            field=positions.fields.PositionField(default='0'),
        ),
    ]
