# Generated by Django 2.0.5 on 2018-08-06 20:57

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20180806_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='index',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
